services:
  postgres:
    image: postgres:18-alpine3.22
    container_name: url_shortener_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - url_shortener_network

  redis:
    image: redis:7-alpine
    container_name: url_shortener_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - url_shortener_network

networks:
  url_shortener_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
