name: CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: pnpm run verify

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag url-shortener:$(date +%s)
      - name: Run the Docker container with docker compose (production)
        run: docker compose -f docker-compose.prod.yml up -d
