name: CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.17.0
          run_install: false
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.10.0
          cache: 'pnpm'

      - name: install dependencies
        run: pnpm install

      - name: run lint
        run: pnpm run lint:ci

      - name: run format
        run: pnpm run format:ci

      - name: run spell
        run: pnpm run spell

      - name: run unit tests
        run: pnpm run test:ci

  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build docker image
        run: docker build -t url-shortener .
